import os
from datetime import datetime


class CodeWriter:
    def __init__(self):
        self.workspace = os.path.expanduser(
            "~/cyprus/workspace/proposals"
        )

    def create_module(self, name, purpose):
        code = f'''"""
{name}.py

Generated by ZETA
{datetime.now()}
"""

class {name.capitalize()}:

    def __init__(self):
        print("{name} module initialized")

    def run(self):
        print("{purpose}")
'''

        filename = os.path.join(self.workspace, f"{name}.py")

        with open(filename, "w") as f:
            f.write(code)

        print(f"[ZETA] Created {filename}")
