import os
from datetime import datetime
from agent.radio.mission_manager import MissionManager
from agent.brain import ask_ai
class ContentCreator:
 def __init__(self):
  self.manager = MissionManager()
  self.output_folder = os.path.expanduser("~/cyprus/workspace/radio_outputs")
  os.makedirs(self.output_folder, exist_ok=True)
 def create_daily_content(self):
  mission = self.manager.next_mission()
  path = os.path.join(self.output_folder, datetime.now().strftime("%Y-%m-%d_%H%M") + "_" + mission.lower().replace(" ", "_") + ".md")
  prompt = f"Write an engaging, culturally rich post for Greek Roots Radio.\nMission target: {mission}.\nInclude tags, music themes, or cultural notes."
  print(f"[ZETA] Requesting Gemini output payload for mission: {mission}...")
  ai_response = ask_ai(prompt)
  body = f"# Greek Roots Radio\n\nMission\n-------\n{mission}\n\nCreated\n-------\n{datetime.now()}\n\nGenerated by\n------------\nZETA Autonomous Radio Division (Powered by Google Gemini AI)\n\n======================================================================\nGENERATED POST COPY:\n======================================================================\n{ai_response}"
  with open(path, "w") as out: out.write(body)
  return {"agent": "ZETA Radio Content Creator", "project": "Greek Roots Radio", "mission": mission, "output": path, "status": "fully written with Gemini AI payload", "created": str(datetime.now())}
