import os
from datetime import datetime

from agent.radio.mission_manager import MissionManager


class ContentCreator:

    def __init__(self):

        self.manager = MissionManager()

        self.output_folder = os.path.expanduser(
            "~/cyprus/workspace/radio_outputs"
        )

        os.makedirs(
            self.output_folder,
            exist_ok=True
        )

    def create_daily_content(self):

        mission = self.manager.next_mission()

        filename = (
            datetime.now().strftime("%Y-%m-%d_%H%M")
            + "_"
            + mission.lower().replace(" ", "_")
            + ".md"
        )

        path = os.path.join(
            self.output_folder,
            filename
        )

        body = f"""# Greek Roots Radio

Mission
-------

{mission}

Created
-------

{datetime.now()}

Generated by

ZETA Autonomous Radio Division
"""

        with open(path, "w") as f:

            f.write(body)

        return {
            "agent": "ZETA Radio Content Creator",
            "project": "Greek Roots Radio",
            "mission": mission,
            "output": path,
            "status": "written",
            "created": str(datetime.now())
        }
