import os
from datetime import datetime


class CodeWriter:

    def __init__(self):

        self.workspace = os.path.expanduser(
            "~/cyprus/workspace/proposals"
        )


    def create_module(self, name, purpose):

        class_name = "".join(
            word.capitalize()
            for word in name.split("_")
        )


        code = f'''"""
{name}.py

Generated by ZETA
{datetime.now()}
"""


class {class_name}:


    def __init__(self):

        self.name = "{name}"

        self.purpose = "{purpose}"


    def status(self):

        return {{
            "module": self.name,
            "purpose": self.purpose,
            "status": "active",
            "created": "{datetime.now()}"
        }}


    def run(self):

        print(
            "[ZETA MODULE]",
            self.name,
            "running"
        )

        return self.status()
'''


        filename = os.path.join(
            self.workspace,
            f"{name}.py"
        )


        with open(filename, "w") as f:
            f.write(code)


        print(
            f"[ZETA] Created {filename}"
        )


        return filename
