import random
from datetime import datetime


class PlannerAgent:

    def __init__(self):

        self.capabilities = [
            "memory",
            "chat",
            "calendar",
            "email",
            "web_search",
            "documents",
            "automation"
        ]


    def generate_plan(self):

        capability = random.choice(
            self.capabilities
        )

        plan = {
            "module": capability,
            "purpose": f"{capability} module generated by ZETA",
            "created": str(datetime.now())
        }

        print(
            f"[Planner] Next capability: {capability}"
        )

        return plan


    # Used by ZETA Supervisor
    def analyse(self):

        recommendation = random.choice(
            self.capabilities
        )

        plan = {
            "recommended_next_build": recommendation,
            "time": str(datetime.now())
        }

        print(
            f"[Planner] Recommended build: {recommendation}"
        )

        return plan
