import json
import os
from datetime import datetime


class PlannerAgent:

    def __init__(self):

        self.goals_file = os.path.expanduser(
            "~/cyprus/data/goals.json"
        )

        self.proposals_dir = os.path.expanduser(
            "~/cyprus/workspace/proposals"
        )


    def _load_goals(self):

        if not os.path.exists(self.goals_file):
            return []

        try:

            with open(self.goals_file, "r") as f:
                data = json.load(f)

            if isinstance(data, dict):
                goals = data.get("active", [])

            elif isinstance(data, list):
                goals = data

            else:
                goals = []

            return sorted(
                goals,
                key=lambda g: g.get("priority", 0),
                reverse=True
            )

        except Exception as e:

            print(f"[Planner] Could not read goals: {e}")
            return []


    def _existing_modules(self):

        modules = set()

        if os.path.exists(self.proposals_dir):

            for file in os.listdir(self.proposals_dir):

                if file.endswith(".py"):
                    modules.add(file[:-3])

        return modules


    def _choose_goal(self):

        goals = self._load_goals()
        existing = self._existing_modules()

        for goal in goals:

            name = goal.get("goal", "").strip()

            status = goal.get(
                "status",
                "active"
            )

            if not name:
                continue

            if status != "active":
                continue

            if name in existing:
                continue

            return goal

        return None


    def generate_plan(self):

        goal = self._choose_goal()

        if goal is None:

            print("[Planner] No active goals left.")
            return None

        module = goal["goal"]

        print(
            f"[Planner] Next capability: {module}"
        )

        return {
            "module": module,
            "purpose": f"{module} module generated by ZETA",
            "created": str(datetime.now()),
            "priority": goal.get("priority", 0)
        }


    def analyse(self):

        goal = self._choose_goal()

        if goal is None:

            print("[Planner] No active goals left.")

            return {
                "recommended_next_build": None,
                "time": str(datetime.now())
            }

        print(
            f"[Planner] Recommended build: {goal['goal']}"
        )

        return {
            "recommended_next_build": goal["goal"],
            "time": str(datetime.now()),
            "priority": goal.get("priority", 0)
        }
